# Site settings
title: Diogo Eiras
email: eiras@outlook.com
description: > 
  Personal blog with some source code snippets and themes about technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://diogoeiras.github.io" # the base hostname & protocol for your site
twitter_username:  diogoseiras
github_username:   diogoeiras
instagram_username: diogoeiras
youtube_username:  FDiogoEiras
facebook_username: diogoeiras

# Build settings
markdown: kramdown
